services:
  ${HOST}:
    hostname: ${HOST}
    container_name: ${HOST}
    image: ${IMAGE}
    dns:
    - 172.17.1.20
    - 172.17.1.21
    ports:
    - "${APP_PORT}:${APP_PORT}"
    - "${SSH_PORT}:22"
    networks:
    - local
networks:
  local:
    driver: bridge