- name: copy app source to host
  ansible.builtin.copy:
    force: yes
    src: projects/{{ app }}
    dest: /tmp/
    mode: preserve

- name: build app source
  make:
    chdir: /tmp/{{ app }}
    target: build

- name: delete app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ app_root_directory }}"

- name: create app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ app_root_directory }}"

- name: deploy app
  ansible.builtin.copy:
    force: yes
    remote_src: yes
    src: /tmp/{{ app }}/artifact/
    dest: "{{ app_root_directory }}"
